version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install aws-sam-cli

  build:
    commands:
      - echo "Deploying to development environment"
      - sam deploy --template-file packaged-template.yaml --config-file samconfig-dev.toml --no-confirm-changeset --no-fail-on-empty-changeset
      - echo "Development deployment completed"

  post_build:
    commands:
      - echo "Validating development deployment"
      - |
        STACK_NAME="commons-service-dev"
        aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].StackStatus' --output text
        if [ $? -eq 0 ]; then
          echo "✅ Development stack deployed successfully"
        else
          echo "❌ Development deployment failed"
          exit 1
        fi